### ISSUE TITLE
Suggestion: Git Submodule KaTeX and QuickJS?

### ISSUE THREAD

**Issue by awwong1** [graemephi/goldmark-qjs-katex#2]
Hello again, would it be better to move the raw quickjs and katex files into separate repositories, referring to them through git submodules?
The QuickJS code used in this repo is already outdated ([quickjs-2020-01-19.tar.xz](https://bellard.org/quickjs/quickjs-2020-01-19.tar.xz)).
Having these separated would make updating external dependencies simpler and keep this repository more modular.

----
Aside, I am very grateful for your work in implementing this feature. Using it locally right now with no issues.
I submitted a PR incorporating your extension in [hugo](https://github.com/gohugoio/hugo). Admittedly, I am not very familiar with golang or C so if there are additional concerns, I am eager to listen.
https://github.com/gohugoio/hugo/issues/6544
https://github.com/gohugoio/hugo/pull/6842

**Comment by graemephi** [comment]
It's outdated, but so is the unofficial git repo linked to on quickjs's website :) Looking through the diff, there are no changes that affect this project.

Looking into it, go's tools don't support submodules. So, if you look at [go-libsass](https://github.com/wellington/go-libsass/blob/master/Makefile) then they have a Makefile that updates a submodule then copies the source into their tree. I can see that being worthwhile for complex dependencies, but both QuickJS and KaTeX are very simple as dependencies go, so I don't think it's all that worthwhile here. (I also have reservations about using git's more complex functionality but that feels like I'm just griping rather than offering a real reason).

I have a hugo fork on my profile with pretty much the exact changes you made. I didn't submit a PR cause its pretty heavyweight (requires cgo, doubles the executable size) and I'd like to add \[ and \( support if it was going to have wider use. Although, I wasn't aware of #6544, I probably would have posted there if I was.

**Comment by jasikpark** [comment]
Perhaps use [godzilla](https://github.com/jingweno/godzilla) or [otto](https://github.com/robertkrimen/otto)? It seems otto supports `js` sans CGO. And I *think* godzilla does as well.
